name             'swap'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures swap'
long_description 'Installs/Configures swap'
version          '0.1.0'
